const WOT_ICON_ALIASES: Record<string, string> = {
  back: 'arrow-left',
  forward: 'arrow-right',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  'arrow-down': 'arrow-down',
  'chevron-right': 'chevron-right',
  'chevron-left': 'chevron-left',
  'chevron-up': 'chevron-up',
  'chevron-down': 'chevron-down',
  plus: 'add',
  'plus-circle': 'add-circle',
  minus: 'decrease',
  close: 'close',
  'close-circle': 'close-circle',
  check: 'check',
  'check-circle': 'check-circle',
  search: 'search',
  refresh: 'refresh',
  gear: 'setting',
  trash: 'delete',
  doc: 'file',
  package: 'goods',
  image: 'picture',
  'image-plus': 'picture',
  'more-h': 'more',
  'more-v': 'ellipsis',
  'star-fill': 'star-filled',
  star: 'star-on',
  'eye-off': 'eye-close',
  eye: 'browse',
  'user-line': 'user',
  'home-shop': 'shop',
  'location-pin': 'location',
  location: 'location',
  phone: 'phone',
  mail: 'mail',
  lock: 'lock-on',
  share: 'share',
  info: 'info-circle',
  help: 'help-circle',
  bell: 'notification',
  wallet: 'wallet',
  gift: 'gift',
  calendar: 'calendar',
  clock: 'time',
  camera: 'camera',
  filter: 'filter',
  edit: 'edit',
  tag: 'discount',
  ruler: 'tools',
  lightning: 'poweroff',
  crown: 'star-filled',
  megaphone: 'notification',
  message: 'chat',
  navigation: 'location',
  'thumb-up': 'thumb-up',
  wechat: 'chat',
  'apple-pay': 'apple',
  'biz-home': 'home',
  'biz-product': 'goods',
  'biz-order': 'a-order-adjustmentcolumn',
  'biz-stats': 'chart-bar',
  'biz-me': 'user-circle',
  'biz-customer': 'usergroup',
  'biz-chat': 'chat',
  'biz-store': 'shop',
  'biz-staff': 'usergroup',
  'biz-marketing': 'notification',
  'biz-plaza': 'layers',
  'biz-member': 'star-filled',
  'biz-withdraw': 'creditcard',
  'biz-commission': 'money-circle',
  'biz-shop-decorate': 'edit',
  'biz-aftersale': 'rollback',
  'biz-receipt': 'file',
}

export function wotIconName(name: unknown): string {
  const normalized = String(name ?? '')
  return WOT_ICON_ALIASES[normalized] ?? normalized
}

export function wotTagType(
  tone: unknown,
): 'default' | 'primary' | 'success' | 'warning' | 'danger' {
  if (tone === 'error') return 'danger'
  if (tone === 'info') return 'primary'
  if (tone === 'highlight') return 'warning'
  if (tone === 'primary' || tone === 'success' || tone === 'warning') return tone
  return 'default'
}
